<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <AvaloniaVersion>12.1.2</AvaloniaVersion>
    <SemiAvaloniaVersion>12.1.0.1</SemiAvaloniaVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'CodeWF.AvaloniaControls.TreeDataGrid' Or '$(MSBuildProjectName)' == 'CodeWF.AvaloniaControls.TreeDataGrid.Themes' Or '$(MSBuildProjectName)' == 'CodeWF.AvaloniaControls.TreeDataGridDemo'">
    <AvaloniaVersion>11.3.7</AvaloniaVersion>
    <SemiAvaloniaVersion>11.3.7.3</SemiAvaloniaVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Controls.DataGrid" Version="12.1.2" />
    <PackageVersion Include="Avalonia.Controls.TreeDataGrid" Version="11.1.1" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.401" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageVersion Include="Semi.Avalonia" Version="$(SemiAvaloniaVersion)" />
    <PackageVersion Include="Semi.Avalonia.DataGrid" Version="12.1.0.1" />
    <PackageVersion Include="Semi.Avalonia.TreeDataGrid" Version="11.1.1.1" />
    <PackageVersion Include="Tmds.DBus.Protocol" Version="0.95.1" />
    <PackageVersion Include="VC-LTL" Version="5.3.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>
