<Project>
  <PropertyGroup>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <DebugType>portable</DebugType>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IncludeSymbols>true</IncludeSymbols>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <UseArtifactsOutput>true</UseArtifactsOutput>
    <ArtifactsPath>$(MSBuildThisFileDirectory)artifacts\</ArtifactsPath>
    <PackageOutputPath>$(ArtifactsPath)packages\</PackageOutputPath>
    <DataGridPackageVersion>12.1.2.11</DataGridPackageVersion>
    <TreeDataGridPackageVersion>11.1.1.16</TreeDataGridPackageVersion>
    <Version Condition="'$(MSBuildProjectName)' == 'CodeWF.AvaloniaControls.DataGrid' Or '$(MSBuildProjectName)' == 'CodeWF.AvaloniaControls.DataGrid.Themes'">$(DataGridPackageVersion)</Version>
    <Version Condition="'$(MSBuildProjectName)' == 'CodeWF.AvaloniaControls.TreeDataGrid' Or '$(MSBuildProjectName)' == 'CodeWF.AvaloniaControls.TreeDataGrid.Themes'">$(TreeDataGridPackageVersion)</Version>
    <Authors>沙漠尽头的狼</Authors>
    <RepositoryUrl>https://github.com/dotnet9/CodeWF.AvaloniaControls.DataGrid</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/dotnet9/CodeWF.AvaloniaControls.DataGrid</PackageProjectUrl>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <RepositoryType>git</RepositoryType>
    <Copyright>https://codewf.com</Copyright>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>
</Project>
