<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <IsPackable>false</IsPackable>
    <ApplicationIcon>..\..\logo.ico</ApplicationIcon>
    <TargetFrameworks>net11.0;net11.0-windows</TargetFrameworks>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.Controls.TreeDataGrid" />
    <PackageReference Include="Semi.Avalonia" />
    <PackageReference Include="VC-LTL" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CodeWF.AvaloniaControls.TreeDataGrid\CodeWF.AvaloniaControls.TreeDataGrid.csproj" />
    <ProjectReference Include="..\CodeWF.AvaloniaControls.TreeDataGrid.Themes\CodeWF.AvaloniaControls.TreeDataGrid.Themes.csproj" />
  </ItemGroup>
</Project>
